import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faRobot,
  faComments,
  faTimes,
  faPaperPlane,
  faCalendarCheck,
  faCalculator,
  faPhone,
  faEnvelope,
  faHeart,
  faThumbsUp,
  faMapPin,
  faClock,
  faEuroSign,
  faUsers,
  faMicrophone,
  faVideo,
  faCamera,
  faLeaf,
} from '@fortawesome/free-solid-svg-icons';

import {
  faWhatsapp,
  faFacebook,
  faInstagram,
  faLinkedin,
  faTiktok,
} from '@fortawesome/free-brands-svg-icons';

// Ajouter les icônes à la bibliothèque
library.add(
  faRobot,
  faComments,
  faTimes,
  faPaperPlane,
  faCalendarCheck,
  faCalculator,
  faPhone,
  faEnvelope,
  faHeart,
  faThumbsUp,
  faMapPin,
  faClock,
  faEuroSign,
  faUsers,
  faMicrophone,
  faVideo,
  faCamera,
  faLeaf,
  faWhatsapp,
  faFacebook,
  faInstagram,
  faLinkedin,
  faTiktok,
);

export {
  faRobot,
  faComments,
  faTimes,
  faPaperPlane,
  faCalendarCheck,
  faCalculator,
  faPhone,
  faEnvelope,
  faSparkles,
  faHeart,
  faThumbsUp,
  faWhatsappBrand,
  faFacebookBrand,
  faInstagramBrand,
  faLinkedinBrand,
  faTiktokBrand,
};